#!/bin/sh /etc/rc.common

START=95
USE_PROCD=1
PROG=/usr/bin/flowdumper

start_service() {
    procd_open_instance
    procd_set_param command $PROG
    procd_set_param respawn ${respawn_threshold:-600} ${respawn_timeout:-5} ${respawn_retry:-5}
    procd_set_param stdout 1 # forward stdout of the command to logd
    procd_set_param stderr 1 # same for stderr
    procd_set_param term_timeout 60 # wait before sending SIGKILL
    procd_close_instance
}